spring.application.name=med-support

spring.datasource.url=jdbc:postgresql://localhost:5432/med_support
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
